# Generated by Django 3.1.3 on 2020-12-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessWhat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_code', models.CharField(db_index=True, default='', max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('answer', models.CharField(default='', max_length=50)),
                ('guess', models.CharField(default='', max_length=50)),
                ('category', models.CharField(db_index=True, default='', max_length=50)),
            ],
        ),
    ]
