# Generated by Django 3.2 on 2021-05-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_guesswhat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrammle_link', models.URLField()),
                ('arranged_link', models.URLField()),
                ('moves', models.CharField(max_length=50)),
            ],
        ),
    ]
