# Generated by Django 3.1.3 on 2020-11-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gap_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesswhat',
            name='guess',
            field=models.CharField(default='', max_length=50),
        ),
    ]
