# Generated by Django 3.1.3 on 2020-11-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_guesswhat_guess'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='optiona',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optionb',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optionc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='optiond',
            field=models.CharField(default='', max_length=100),
        ),
    ]
