# Generated by Django 3.1.3 on 2020-11-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20201127_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='guess',
            field=models.CharField(default='', max_length=100),
        ),
    ]
